from .superb.asr import SuperbASR
from .superb.er import SuperbER
from .superb.ic import SuperbIC
from .superb.pr import SuperbPR
from .superb.qbe import SuperbQBE
from .superb.sd import SuperbSD
from .superb.sf import SuperbSF
from .superb.sid import SuperbSID
from .superb.sv import SuperbSV
from .hear.dcase_2016_task2 import Dcase2016Task2
from .hear.maestro import Maestro
from .hear.beijing_opera import BeijingOpera
from .hear.esc50 import ESC50
from .hear.gunshot import Gunshot
from .hear.libricount import LibriCount
from .hear.stroke import Stroke
from .hear.tonic import Tonic
from .hear.vox_lingua import VoxLingua
from .hear.nsynth5hr import Nsynth5hr
from .hear.gsc5hr import GSC5hr
from .hear.fsd import FSD50k
from .hear.crema_d import CremaD
from .hear.gtzan import Gtzan
from .hear.gtzan_music_speech import GtzanMusicSpeech
from .hear.fsd import FSD50k
from .hear.vocal import Vocal
