name: CI

on:
  # Trigger the workflow on push to main or any pull request
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
        torchaudio-version: [0.12.1, 0.13.1, 2.0.2, 2.1.0]
          # espnet use 'torchaudio.models.hubert_pretrain_model' with 'feature_grad_mult' option
          # which is available after torchaudio==0.12.0

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1-dev sox git git-lfs

    - name: Upgrade pip and wheel
      run: pip3 install --upgrade pip wheel

    - name: Install dependencies for tests
      run: pip3 install -r requirements/dev.txt

    # This can be very helpful for debugging
    # The action can create a SSH server for you to connect. After you
    # log into the machine hosted by GitHub, it becomes easy to debug
    # why the CI fails on a specific machine.

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Run tox for common upstream
      run: |
        tox -e common_upstream-audio${{ matrix.torchaudio-version }}-espnet -- -k test_specific_upstream --upstream_names espnet_hubert_base_iter1

    # Not all upstreams will be tested on CI since this will take too much time
    # To test all upstreams, run tox locally with '-e all_upstream'

    # - name: Run tox for all other functionalities
    #   run: |
    #     tox -e all_others-deps_all-audio${{ matrix.torchaudio-version }}
